# Generated by Django 2.2.6 on 2019-11-02 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lic_num', models.IntegerField(db_column='lic_num', max_length=8)),
                ('lic_date', models.DateField(db_column='lic_date')),
                ('lic_status', models.CharField(db_column='lic_status', max_length=20)),
                ('lic_entry_date', models.DateTimeField(db_column='lic_entry_date')),
                ('comp_addr', models.CharField(db_column='comp_addr', max_length=100)),
                ('comp_fias_code', models.CharField(db_column='comp_fias_code', max_length=36)),
                ('comp_name', models.CharField(db_column='comp_name', max_length=264)),
                ('comp_inn', models.IntegerField(db_column='comp_inn', max_length=12)),
                ('comp_ogrn', models.IntegerField(db_column='comp_ogrn', max_length=13)),
                ('comp_house_count', models.IntegerField(db_column='comp_house_count')),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_addr', models.CharField(db_column='House_addr', max_length=264)),
                ('House_fias_code', models.CharField(blank=True, db_column='House_fias_code', max_length=36, null=True)),
                ('House_reg_inc', models.DateTimeField(blank=True, db_column='House_reg_inc', null=True)),
                ('House_man_start', models.DateField(blank=True, db_column='House_man_start', null=True)),
                ('House_man_end', models.DateField(blank=True, db_column='House_man_end', null=True)),
                ('House_reg_exc', models.DateTimeField(blank=True, db_column='House_reg_exc', null=True)),
                ('House_reg_exc_base', models.CharField(db_column='House_reg_exc_base', max_length=40)),
                ('House_198data', models.CharField(db_column='House_198data', max_length=12)),
                ('House_reg_pub', models.CharField(db_column='House_reg_pub', max_length=12)),
                ('geo_lat', models.FloatField(db_column='geo_lat')),
                ('geo_lon', models.FloatField(db_column='geo_lon')),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Company')),
            ],
        ),
    ]
